version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    tty: true

  db:
    image: mysql:latest
    container_name: mysql_db_stock
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GSB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
