version: "3.8"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    tty: true

  db:
    image: mariadb:latest
    container_name: mariadb_db_stock
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GSB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./config/script_db.sh:/docker-entrypoint-initdb.d/script_db.sh
      - ./config/GSB.sql:/docker-entrypoint-initdb.d/GSB.sql
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
